---
title: "Tanzania Maize Yield Forecast"
author: "Dr. -Ing. MISK Benson Kenduiywo"
csl: "apa-6th-edition.csl"
output: 
   html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    number_sections: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=60))
opts_knit$set(global.par = TRUE)
```

## RHEAS forecasts

<!-- Load and aggregate RHEAS simulated Leaf Area Index (LAI), Water stress and Grain Weight Average Dry (GWAD) across different ensembles. Extract year from dates (we will use harvest year). -->

```{r rh1, echo=FALSE, message=F, warning=FALSE}
rm(list = ls(all=TRUE))
unlink(".RData")
root <- "D:/RCMRD/Data/Yields/"

formatdf <- function(filename){
  tt <- read.csv(filename, stringsAsFactors =  FALSE)
  tt$harvest <- as.Date(tt$harvest)
  tt$planting <- as.Date(tt$planting)
  tt$date <- format(tt$harvest, format = "%Y")
  names(tt)[3] <- "Region"
  tt$Region <- toupper(tt$Region)
  return(tt)
}

bi <- formatdf(paste0(root, "RHEAS/tanzania_tamsat_25km_districts_bimod_dssatTable_2000_2022_100kg.csv"))

un <- formatdf(paste0(root, "RHEAS/tanzania_tamsat_25km_districts_unimod_dssatTable_2000_2022_100kg.csv"))
```


Maize unit production forecasts (Mt/ha) was done based on 
three maize growing seasons in Tanzania:

1) Season 1: OND (SRSD) October -- February/March.
2) Season 2: MAM February/March -- August 
3) Season 3: Long Rain (LR) November -- August 

<!-- So we will aggregate the metrics and yield forecast per district with this condition using the function `RH_metrics`. -->

```{r rh2, echo=FALSE, message=F, warning=FALSE}
RH_metrics <- function(rh, sStart, sEnd, season){
  rh <- subset(rh, format(as.Date(rh$planting), "%m") %in% sStart & format(as.Date(rh$harvest), "%m") %in% sEnd)
  rh$Season <- season
  rh <- aggregate(rh[,c("wsgd","lai","gwad"), drop=FALSE], rh[,c("Region","date", "Season"), drop=FALSE], mean, na.rm=T)
  
  
  return(rh)
}
# Unimodal season:  October--August (LR)
sStart <- c("09", "10", "11", "12", "01","02", "03", "04")
sEnd <- c("02", "03", "04", "05", "06", "07", "08")
rh_u <- RH_metrics(un, sStart, sEnd, "LR")

#Bimodal season A (OND): September--March
sStart <- c("09", "10", "11")
sEnd <- c("01","02", "03")
rh_a <- RH_metrics(bi, sStart=sStart, sEnd=sEnd, "OND")

#Bimodal season B (MAM): January--August
sStart <- c("01", "02", "03", "04")
sEnd <- c("05", "06", "07", "08")
rh_b <- RH_metrics(bi, sStart=sStart, sEnd=sEnd, "MAM")

# Long Rain
#lr <- aggregate(tt[,c("wsgd","lai","gwad"), drop=FALSE], tt[,c("Region","date"), drop=FALSE], mean, na.rm=T)
#Merge all
rh <- do.call(rbind, list(rh_u, rh_a, rh_b))

```

<!-- Convert RHEAS yields from kg/ha to MT/ha. -->

```{r rh3, echo=FALSE, message=F, warning=FALSE}
rh$gwad <- rh$gwad/1000
#Remove values along the lake region
rh$gwad[rh$Region=="LAKE VICTORIA"] <- NA
```


<!-- ## Visualization -->

<!-- Add shapefile for visualization. -->

```{r, v1, echo=FALSE, message=F, warning=FALSE}
library(raster)
filename <- "D:/Adm data/Tanzania/gadm36_TZA_2.shp"
tza <- shapefile(filename)
names(tza)[7] <- "Region"
tza$Region <- toupper(tza$Region)
```


<!-- Check and format Region names to be consistent in both the RHEAS and administrative boundaries. Here we check which regions are mission from RHEAS predictions. -->

```{r v2, echo=FALSE, message=F, warning=FALSE, results='hide'}
c <- sort(unique(tza$Region))
c[!c %in% sort(unique(rh$Region))]
```

<!-- Merge RHEAS and Admin data. -->
 
```{r v3, echo=FALSE, message=F, warning=FALSE}
year <- 2022
temp <- rh[, c("Region", "date", "gwad", "lai", "wsgd", "Season")]
temp$Season[temp$date==2023] <- "OND_2023"
temp <- reshape(temp, idvar = c("Region","date"), timevar = "Season", v.names  = c("gwad", "lai", "wsgd"),direction = "wide")
tza1 <-  merge(tza[,c("Region", 'NAME_1')], temp[temp$date==year,], by = "Region", duplicateGeoms=TRUE)
tza2 <-  merge(tza[,c("Region", 'NAME_1')], temp[temp$date==year+1,], by = "Region", duplicateGeoms=TRUE)

```


<!-- ### Map of yields -->

<!-- Visualize RHEAS predicted yields spatially for *all seasons*.  -->

```{r v4, echo=FALSE, message=F, warning=FALSE}
library(tmap)
library(mapview)
tmap_mode("view")

tzac <-  merge(tza[,"Region"], temp[temp$date==year+1, c("gwad.OND_2023","Region")], by = "Region")
tzac <-  merge(tzac, temp[temp$date==year, c("gwad.OND","gwad.MAM","gwad.LR","Region")], by = "Region")


 map <- tm_shape(tzac, name="2023 OND Maize yield (MT/ha)") +
  tm_fill(col= c("gwad.OND_2023", "gwad.OND", "gwad.MAM", "gwad.LR"),   title=c("2023 OND Yield (MT/ha)", "2022 OND Yield (MT/ha)", "2022 MAM Yield (MT/ha)", "2022 LR Yield (MT/ha)"), textNA = "No data", breaks = seq(0.4,4, 0.6)) +
   tm_facets(sync = TRUE, ncol = 2, nrow=2) +
   tm_layout(title.size =5, panel.label.size=6)+
   tm_format("World")
 map 
 #tmap_arrange(map_a, map_b, map_c,map_d, ncol = 2, sync = T)

tmap_save(map, scale =1.6, dpi= 600, filename="D:/RCMRD/Code/TZA_Yields_2022.png")
##Other plotting options see http://www.nickeubank.com/wp-content/uploads/2015/10/RGIS3_MakingMaps_part1_mappingVectorData.html#multiple-layers-with-spplot
```



## Annual Seasonal Trends

Maize yield trends for the last 15 years.
 
```{r bb1, echo=FALSE, message=F, warning=FALSE}
library(ggplot2)
temp <- rh[rh$date > 2007,]
p <- ggplot(temp, aes(x = date, y = gwad))
 
p <- p + geom_boxplot(
   aes(fill = Season),
   position = position_dodge(0.9) 
   ) +
   scale_fill_manual(values = c("#999999", "#E69F00", "green"))+
   ggtitle("Annual Seasonal  Maize Yield Trend")+
   labs(y = "Yield (MT/ha)", x = "Year")
 p

```
 

